DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
 id SERIAL PRIMARY KEY NOT NULL,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 menu_id INTEGER REFERENCES menu(id) ON DELETE CASCADE,
 menu_name VARCHAR(255) NOT NULL,
 price INTEGER NOT NULL,
 quantity INTEGER NOT NULL,
 img VARCHAR(255)
);


